### ISSUE TITLE
Ubuntu 21.10 broken GPU driver

### ISSUE THREAD

**Issue by psyborg55** [deeptho/linux_media#3]
When following install instructions on fresh ubuntu 21.10 system, installed modules will break amdgpu driver

The solution involves building latest driver version instead of the one from 28.9.2021. and reordering few kernel patches

```
mkdir ~/blindscan_kernel
cd  ~/blindscan_kernel

#check out the actual drivers. This uses the default branch which is called deepthought
git clone --depth=1  https://github.com/deeptho/linux_media.git ./media

#checkout a copy of media_build. Standard media_build should work as well
git clone https://github.com/tbsdtv/media_build.git

cd media_build

#edit "media_build/backports/backports.txt"
#remove lines 
#        [5.15.1023]
#        add v5.15_container_of.patch
#
#        [5.14.1023]
#and move line
#        add v5.14_bus_void_return.patch
#to
#        [5.12.1023]
#section

make dir DIR=../media
make distclean
make allyesconfig
make -j8
sudo make install
```

**Comment by deeptho** [comment]
Does this still happen with the current blindscan drivers?

**Comment by psyborg55** [comment]
Yes. I had build of https://github.com/deeptho/linux_media/commit/8530625bc8b9ca1933463b5aeff4f355e2f8fbf2
I cloned latest trees and built according to the instructions.
After restart dmesg says the driver version is still https://github.com/deeptho/linux_media/commit/8530625bc8b9ca1933463b5aeff4f355e2f8fbf2 and GPU drivers are not working. 5.13.0-22 kernel, no idea if anything changed with newer kernel as i dont intend to do any system  updates now.

cec module appears to break things
![20220516_145431](https://user-images.githubusercontent.com/15853469/168597817-ebae8c3d-0afb-44e5-8dfa-1212380cba45.jpg)

**Comment by crazycat69** [comment]
Disable RC, CEC core in media_build and install media modules in extra dir
https://github.com/tbsdtv/media_build/tree/extra
https://github.com/tbsdtv/media_build/commit/a32f8a22545f9666a9cb415191b03c757ac15831
https://github.com/tbsdtv/media_build/blob/extra/install.sh

**Comment by deeptho** [comment]
Hi Crazycat,
good to hear from you. I follow the news from your country closely (ICTV 
on 13.0E) and wish you all the best.

About the graphics driver problem: The earlier instructions for the blindscan drivers used a specific older version of media_build, so this might be a difference. It is difficult for me to comment as I do not experience the problem myself.

**Comment by deeptho** [comment]
Try  the new installatiom instructions in REAME.md, after updating media_build.
This follows the instructions of crazycat

**Comment by deeptho** [comment]
Should be fixed now (new installation procedure)

**Comment by psyborg55** [comment]
Install procedure is broken, as usual.
One problem is in kernel version parsing from backports.txt
It appears the script tries to apply patches for all kernel versions higher than actual system kernel version

**Comment by deeptho** [comment]
Yes, there is something seriously wrong with this whole media_build approach. Not sure how to solve it.
We have kernel/media_build/tbs (crazycat) media_build/ neumo

4 levels of incompatibilities.

**Comment by crazycat69** [comment]
https://github.com/tbsdtv/media_build/blob/extra/install.sh

**Comment by psyborg55** [comment]
install.sh works when correct patches are applied.
on 20.04.4 wrong patches applied, no drivers built, process finished and all the media drivers from modules/kernel gone!
then the output as on screenshot above
the script shouldn't even touch modules/kernel
to fix: reinstall linux-modules and linux-modules-extra for running kernel version, start all over after manually editing backports.txt

**Comment by deeptho** [comment]
I know install.sh works, thanks to crazycat. But it also has problems. 
It doesn't take into account that on ubuntu some other files (Modules.symvers
etc.) are touched by media_build in a non-reversible manner.  So people use it, their graphics card stops working because they make a mistake. install.sh clears this up only partially and nothing works. Probably one factor is some kind of automation that
happens on ubuntu, which I do not know very well. In any case the end result is the same: a failked media_build followed 
by erasting the "extra" modules leaves the system in a bad state. The only thing that works is reinstall the kernel-modules
with apt. Of course by the time you realize that, 1 day has gone by.

Another issue is that when errors occur, the modules that have been built 
are installed anyway. The error messages are hidden in between a long list of compiler warnings and people do not even realize
they have installed broken modules. That one is actually easy to fix. I will report it sometime.

However, my comments om media_build were not about install.sh. Rather, it is the whole process that sucks. The patches probably come from the regular media_build. They seem to work on one platform/kernel and crazycat cannot test on all possible combinations. In any case, reporting  bugs to media_build is not trivial either. I opened a ticket 18 days ago. No response. All of this is done by volunteers, so it is even understandable that people cannot react quickly. But what is the alternative? Making yet another version of media_build?

Anyway at some future time, my plan is to work on out-of-kernel patches. People can then install whatever kernel
they want and compile the additional modules directly. This will be restricted to a few selected cards (the ones I have)
but the intent is to keep both the interface between the new dvbapi (lets us call it neumoapi) and existing modules
working and keep backwards compatibility on the user side. At the same time there will be this new neumoapi that 
makes it easier to support advanced features.

It is all a bit tricky. Also distributions these days do not even provide the kernel sources for all available kernels.
So even this is not a full solution. Integration in the official kernel is even more problematic due to licensing issues
and code quality (even my own code is probably not good enough)
